<?php include('header_project.php'); ?>
<?php include('connect_project.php');?>
<?php //include('session.php'); ?> 
<?php error_reporting(E_ERROR); ?>
<?php session_start(); 
$get_id=$_SESSION['tid'];?>
<?php
$par_query=mysql_query("select * from tutor where tutor_id='$get_id'")or die(mysql_error());
$row1=mysql_fetch_array($par_query);
?>
<?php $batch_id= $_POST['batch_id']; ?>


<script type="text/javascript">     
        function PrintDiv() {    
           var divToPrint = document.getElementById('table');
           var popupWin = window.open('', '_blank', 'width=300,height=300');
           popupWin.document.open();
           popupWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
            popupWin.document.close();
                }
     </script>

<body>

    <div class="row-fluid">
        <div class="span12">

          <?php include('navbar_project.php'); ?> 

            <div class="container">

                <div class="row-fluid">

                    <div class="span12">

                        <div class="hero-unit-3">
						<a href="tutor_home_project.php" class="btn btn-success"><i class="icon-home icon-large"></i>&nbsp;Home</a>
							<a href="report1_tut_project.php" class="btn btn-success"><i class="icon-arrow-left icon-large"></i>&nbsp;Back</a>
                            <br><br>
							
							<div id="table">
							
                           <table width="400" border="0" align="center" cellpadding="0" cellspacing="1" bgcolor="#CCCCCC" >
							
                                <thead>
						
								<tr><th colspan="5"><img src="admin/images/logo2.png" width="500" height="100"/></th></tr>
								<tr><th colspan="5">Monthly Class Test Marks</th></tr>
								<tr><th colspan="5">Batch ID:<?php echo $batch_id; ?></th></tr>
								<tr><th>&nbsp;</th></tr>
								<tr><th>&nbsp;</th></tr>
																
                                    <tr>
                                        
                                        <th>Student ID</th>
										<th>Student Name</th>
										<th>Month</th>
										<th>Class Test No</th>										
										<th>Mark</th>
										
                                    </tr>
                                </thead>
								
                                <tbody>
                                    <?php
                                    $query = mysql_query("select * from class_test,batch,student where class_test.batch_id=batch.batch_id and 
															batch.batch_id='$batch_id' and student.stu_id=class_test.stu_id") or die(mysql_error());
                                    while ($row = mysql_fetch_array($query)) {
                                        $class_test_id = $row['class_test_id'];
                                        ?>
									
                                    <tr class="odd gradeX">
                                    
                                        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $row['stu_id']; ?></td> 
                                        <td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $row['stu_fname'] . " " . $row['stu_lname']; ?></td> 
										<td>&nbsp;&nbsp;&nbsp;<?php echo $row['month']; ?></td> 
										<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $row['class_test_no']; ?></td>
										<td>&nbsp;&nbsp;&nbsp;<?php echo $row['mark']; ?></td> 
										
                                    </tr>
                                <?php } ?>
								<tr><td>&nbsp;</td></tr>
								<tr><td>&nbsp;</td></tr>
								<tr><td colspan="5">Report Generated By:<?php echo $row1['tut_fname'] . " " . $row1['tut_lname']; ?></td></tr>
								<tr><td>&nbsp;</td></tr>
								<tr><td colspan="5">Date:<?php echo date("Y-m-d"); ?></td></tr>
                                </tbody>
                            </table>
							</div>
							<a href="" onclick="PrintDiv();" class="btn btn-success"><i class="icon-print icon-large"></i>&nbsp;Print</a>
							
                        </div>
                    </div>
                </div>
                <?php include('footer_project.php'); ?>
            </div>
        </div>
    </div>

</body>
</html>